services:

  app:
    depends_on:
      meilisearch:
        condition: service_started

  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: ez-php-webhook-meilisearch
    ports:
      - "${MEILISEARCH_PORT:-7700}:7700"
    environment:
      MEILI_MASTER_KEY: "${MEILISEARCH_KEY:-}"
      MEILI_NO_ANALYTICS: "true"
    tmpfs:
      - /meili_data
